name: JOSS paper preview

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build JOSS paper (Docker official)
        run: |
          docker pull openjournals/joss
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            openjournals/joss

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper-pdf
          path: paper/paper.pdf
