name: JOSS paper preview

on:
  push:
    paths:
      - paper/**
  pull_request:
    paths:
      - paper/**

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build JOSS paper
        uses: openjournals/openjournals-docker-action@v1
        with:
          journal: joss
          r-version: '4.3'
